#-------------------------------
# General Site Settings
title: YangRok's
logo: logo.svg # You can add own logo.
description: YangRok's blog


#-------------------------------
# Author Settings
author:
  name: YangRok Choi
  image: main.jpg
  say-hello: Hello, I’m <strong>YangRok Choi</strong>
  bio: Current Ph.D program at <strong>Korea University</strong>. My main research field is <strong>Civil Engineering</strong>. And recently I'm interested in applying <strong>Deep Learning</strong> in <strong>Civil Engineering</strong>.


#-------------------------------
# Contact links
github: https://github.com/YangRokChoi/
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: YangRok # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
